delete book from store if there is no book return an error
xm6264jz/readinglist pull request #19
Opened 2020-09-19 17:13 UTC by xm6264jz

@yp0975eu  Now this code works. Have a look at it and review. Thanks

2020-09-19 17:17 UTC, yp0975eu requested changes
This pull request doesn't look complete.

2020-09-19 17:17 UTC, yp0975eu commented on main.py
> +
@xm6264jz , There's no delete option here.

2020-09-19 17:19 UTC, xm6264jz commented
@yp0975eu  I will make a change to that

2020-09-19 17:36 UTC, xm6264jz commented
@yp0975eu you select it through the menu option. There is a second commit. that makes it 2 commits

2020-09-19 17:39 UTC, xm6264jz commented
@yp0975eu I get it now where the mistake is... I will make a change to it

2020-09-19 21:43 UTC, yp0975eu reviewed
There's a duplicate option `Q`. Can you remove the one you added on line 29 and move the one on line 36 directly underneath option 7?

2020-09-19 21:43 UTC, yp0975eu commented on main.py
> +    menu.add_option('Q', 'Quit', quit_program)
There are two Q options. 1 on line 29 and one on line 36

2020-09-20 01:39 UTC, xm6264jz commented
@yp0975eu I have deleted one of the Q options.

2020-09-20 14:46 UTC, yp0975eu approved these changes

2020-09-20 14:46 UTC, yp0975eu commented on bookstore.py
Line 197 - 199 white space is unnecessary

2020-09-20 14:46 UTC, yp0975eu commented
@xm6264jz, I've approved this pull request.

2020-09-20 14:47 UTC, merged